//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foms
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://khfoms.ru/bdz")]
    public partial class ResponseData : object
    {
        
        private string ResultField;
        
        private string MessageField;
        
        private Foms.PersonData personDataField;
        
        private Foms.AttachmentData attachmentDataField;
        
        private Foms.PolisData polisDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Foms.PersonData personData
        {
            get
            {
                return this.personDataField;
            }
            set
            {
                this.personDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Foms.AttachmentData attachmentData
        {
            get
            {
                return this.attachmentDataField;
            }
            set
            {
                this.attachmentDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Foms.PolisData polisData
        {
            get
            {
                return this.polisDataField;
            }
            set
            {
                this.polisDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonData", Namespace="http://khfoms.ru/bdz")]
    public partial class PersonData : object
    {
        
        private string PersonIdField;
        
        private string PersonENPField;
        
        private string PersonSurnameField;
        
        private string PersonFirstnameField;
        
        private string PersonSecnameField;
        
        private string PersonBirthdayField;
        
        private string PersonSexField;
        
        private string PersonBirthplaceField;
        
        private string PersonSNILSField;
        
        private Foms.PersonAddress personAddressField;
        
        private string PersonCitizenshipField;
        
        private string DocumentTypeField;
        
        private string DocumentSerField;
        
        private string DocumentNumField;
        
        private string DocumentDateField;
        
        private string DocumentOrgField;
        
        private string PersonSocStatusField;
        
        private string PersonCategoryField;
        
        private string PersonDeathDateField;
        
        private string PersonPhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonId
        {
            get
            {
                return this.PersonIdField;
            }
            set
            {
                this.PersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string PersonENP
        {
            get
            {
                return this.PersonENPField;
            }
            set
            {
                this.PersonENPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PersonSurname
        {
            get
            {
                return this.PersonSurnameField;
            }
            set
            {
                this.PersonSurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PersonFirstname
        {
            get
            {
                return this.PersonFirstnameField;
            }
            set
            {
                this.PersonFirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PersonSecname
        {
            get
            {
                return this.PersonSecnameField;
            }
            set
            {
                this.PersonSecnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PersonBirthday
        {
            get
            {
                return this.PersonBirthdayField;
            }
            set
            {
                this.PersonBirthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string PersonSex
        {
            get
            {
                return this.PersonSexField;
            }
            set
            {
                this.PersonSexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string PersonBirthplace
        {
            get
            {
                return this.PersonBirthplaceField;
            }
            set
            {
                this.PersonBirthplaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PersonSNILS
        {
            get
            {
                return this.PersonSNILSField;
            }
            set
            {
                this.PersonSNILSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public Foms.PersonAddress personAddress
        {
            get
            {
                return this.personAddressField;
            }
            set
            {
                this.personAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PersonCitizenship
        {
            get
            {
                return this.PersonCitizenshipField;
            }
            set
            {
                this.PersonCitizenshipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string DocumentType
        {
            get
            {
                return this.DocumentTypeField;
            }
            set
            {
                this.DocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string DocumentSer
        {
            get
            {
                return this.DocumentSerField;
            }
            set
            {
                this.DocumentSerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string DocumentNum
        {
            get
            {
                return this.DocumentNumField;
            }
            set
            {
                this.DocumentNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string DocumentDate
        {
            get
            {
                return this.DocumentDateField;
            }
            set
            {
                this.DocumentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string DocumentOrg
        {
            get
            {
                return this.DocumentOrgField;
            }
            set
            {
                this.DocumentOrgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string PersonSocStatus
        {
            get
            {
                return this.PersonSocStatusField;
            }
            set
            {
                this.PersonSocStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string PersonCategory
        {
            get
            {
                return this.PersonCategoryField;
            }
            set
            {
                this.PersonCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string PersonDeathDate
        {
            get
            {
                return this.PersonDeathDateField;
            }
            set
            {
                this.PersonDeathDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string PersonPhone
        {
            get
            {
                return this.PersonPhoneField;
            }
            set
            {
                this.PersonPhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentData", Namespace="http://khfoms.ru/bdz")]
    public partial class AttachmentData : object
    {
        
        private string CodeMOField;
        
        private string RegionField;
        
        private string RegionNameField;
        
        private string RegionTypeField;
        
        private string AttachTypeField;
        
        private string AttachBeginDateField;
        
        private string AttachEndDateField;
        
        private string AttachReasonField;
        
        private string DetachReasonField;
        
        private string DoctorSnilsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeMO
        {
            get
            {
                return this.CodeMOField;
            }
            set
            {
                this.CodeMOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionType
        {
            get
            {
                return this.RegionTypeField;
            }
            set
            {
                this.RegionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string AttachType
        {
            get
            {
                return this.AttachTypeField;
            }
            set
            {
                this.AttachTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string AttachBeginDate
        {
            get
            {
                return this.AttachBeginDateField;
            }
            set
            {
                this.AttachBeginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string AttachEndDate
        {
            get
            {
                return this.AttachEndDateField;
            }
            set
            {
                this.AttachEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string AttachReason
        {
            get
            {
                return this.AttachReasonField;
            }
            set
            {
                this.AttachReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string DetachReason
        {
            get
            {
                return this.DetachReasonField;
            }
            set
            {
                this.DetachReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string DoctorSnils
        {
            get
            {
                return this.DoctorSnilsField;
            }
            set
            {
                this.DoctorSnilsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolisData", Namespace="http://khfoms.ru/bdz")]
    public partial class PolisData : object
    {
        
        private string PolisNumField;
        
        private string PolisTypeField;
        
        private string PolisBeginDateField;
        
        private string PolisEndDateField;
        
        private string PolisCloseDateField;
        
        private string PolisSMOField;
        
        private string PolisCloseReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolisNum
        {
            get
            {
                return this.PolisNumField;
            }
            set
            {
                this.PolisNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolisType
        {
            get
            {
                return this.PolisTypeField;
            }
            set
            {
                this.PolisTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PolisBeginDate
        {
            get
            {
                return this.PolisBeginDateField;
            }
            set
            {
                this.PolisBeginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PolisEndDate
        {
            get
            {
                return this.PolisEndDateField;
            }
            set
            {
                this.PolisEndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PolisCloseDate
        {
            get
            {
                return this.PolisCloseDateField;
            }
            set
            {
                this.PolisCloseDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PolisSMO
        {
            get
            {
                return this.PolisSMOField;
            }
            set
            {
                this.PolisSMOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string PolisCloseReason
        {
            get
            {
                return this.PolisCloseReasonField;
            }
            set
            {
                this.PolisCloseReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonAddress", Namespace="http://khfoms.ru/bdz")]
    public partial class PersonAddress : object
    {
        
        private string AddressField;
        
        private string RegionField;
        
        private string SubRegionField;
        
        private string CityField;
        
        private string StreetField;
        
        private string HouseField;
        
        private string CorpusField;
        
        private string FlatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubRegion
        {
            get
            {
                return this.SubRegionField;
            }
            set
            {
                this.SubRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string House
        {
            get
            {
                return this.HouseField;
            }
            set
            {
                this.HouseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Corpus
        {
            get
            {
                return this.CorpusField;
            }
            set
            {
                this.CorpusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Flat
        {
            get
            {
                return this.FlatField;
            }
            set
            {
                this.FlatField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://khfoms.ru/bdz", ConfigurationName="Foms.IMiacBDZServiceIdent")]
    public interface IMiacBDZServiceIdent
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_FIO", ReplyAction="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_FIOResponse")]
        Foms.ResponseData GetPersonInfo_FIO(string userId, string surname, string firstname, string patronymic, string birthday, string UserName, string UserPassword, bool isIPRAfirst, int MIS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_FIO", ReplyAction="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_FIOResponse")]
        System.Threading.Tasks.Task<Foms.ResponseData> GetPersonInfo_FIOAsync(string userId, string surname, string firstname, string patronymic, string birthday, string UserName, string UserPassword, bool isIPRAfirst, int MIS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_SNILS", ReplyAction="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_SNILSResponse")]
        Foms.ResponseData GetPersonInfo_SNILS(string userId, string snils, string UserName, string UserPassword, bool isIPRAfirst, int MIS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_SNILS", ReplyAction="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_SNILSResponse")]
        System.Threading.Tasks.Task<Foms.ResponseData> GetPersonInfo_SNILSAsync(string userId, string snils, string UserName, string UserPassword, bool isIPRAfirst, int MIS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_Polis", ReplyAction="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_PolisResponse")]
        Foms.ResponseData GetPersonInfo_Polis(string userId, string polis, string UserName, string UserPassword, bool isIPRAfirst, int MIS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_Polis", ReplyAction="http://khfoms.ru/bdz/IMiacBDZServiceIdent/GetPersonInfo_PolisResponse")]
        System.Threading.Tasks.Task<Foms.ResponseData> GetPersonInfo_PolisAsync(string userId, string polis, string UserName, string UserPassword, bool isIPRAfirst, int MIS);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IMiacBDZServiceIdentChannel : Foms.IMiacBDZServiceIdent, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class MiacBDZServiceIdentClient : System.ServiceModel.ClientBase<Foms.IMiacBDZServiceIdent>, Foms.IMiacBDZServiceIdent
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MiacBDZServiceIdentClient() : 
                base(MiacBDZServiceIdentClient.GetDefaultBinding(), MiacBDZServiceIdentClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMiacBDZServiceIdent.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiacBDZServiceIdentClient(EndpointConfiguration endpointConfiguration) : 
                base(MiacBDZServiceIdentClient.GetBindingForEndpoint(endpointConfiguration), MiacBDZServiceIdentClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiacBDZServiceIdentClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MiacBDZServiceIdentClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiacBDZServiceIdentClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MiacBDZServiceIdentClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MiacBDZServiceIdentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Foms.ResponseData GetPersonInfo_FIO(string userId, string surname, string firstname, string patronymic, string birthday, string UserName, string UserPassword, bool isIPRAfirst, int MIS)
        {
            return base.Channel.GetPersonInfo_FIO(userId, surname, firstname, patronymic, birthday, UserName, UserPassword, isIPRAfirst, MIS);
        }
        
        public System.Threading.Tasks.Task<Foms.ResponseData> GetPersonInfo_FIOAsync(string userId, string surname, string firstname, string patronymic, string birthday, string UserName, string UserPassword, bool isIPRAfirst, int MIS)
        {
            return base.Channel.GetPersonInfo_FIOAsync(userId, surname, firstname, patronymic, birthday, UserName, UserPassword, isIPRAfirst, MIS);
        }
        
        public Foms.ResponseData GetPersonInfo_SNILS(string userId, string snils, string UserName, string UserPassword, bool isIPRAfirst, int MIS)
        {
            return base.Channel.GetPersonInfo_SNILS(userId, snils, UserName, UserPassword, isIPRAfirst, MIS);
        }
        
        public System.Threading.Tasks.Task<Foms.ResponseData> GetPersonInfo_SNILSAsync(string userId, string snils, string UserName, string UserPassword, bool isIPRAfirst, int MIS)
        {
            return base.Channel.GetPersonInfo_SNILSAsync(userId, snils, UserName, UserPassword, isIPRAfirst, MIS);
        }
        
        public Foms.ResponseData GetPersonInfo_Polis(string userId, string polis, string UserName, string UserPassword, bool isIPRAfirst, int MIS)
        {
            return base.Channel.GetPersonInfo_Polis(userId, polis, UserName, UserPassword, isIPRAfirst, MIS);
        }
        
        public System.Threading.Tasks.Task<Foms.ResponseData> GetPersonInfo_PolisAsync(string userId, string polis, string UserName, string UserPassword, bool isIPRAfirst, int MIS)
        {
            return base.Channel.GetPersonInfo_PolisAsync(userId, polis, UserName, UserPassword, isIPRAfirst, MIS);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMiacBDZServiceIdent))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMiacBDZServiceIdent))
            {
                return new System.ServiceModel.EndpointAddress("http://7.11.120.7:5000/MiacBDZService/basicHttp");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MiacBDZServiceIdentClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMiacBDZServiceIdent);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MiacBDZServiceIdentClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMiacBDZServiceIdent);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMiacBDZServiceIdent,
        }
    }
}
